### ISSUE TITLE
Higher priority issue with "Chip Returns" mod and "Sonic Unleashed HUD" mod

### ISSUE THREAD

**Issue by shaum257** [hedge-dev/HE1ML#1]
Whenever I click on Save and Play, it prompts me with an error saying that the "Chip Returns" mod must be higher priority than "Sonic Unleashed HUD" mod, and won't let me start the game despite both mods being in the correct load order. 
This problem did not occur when HMM was using CPKREDIR.

**Comment by Sajidur78** [comment]
Due to some breaking changes in the mod loader some mods that used odd behaviour for priority checks aren't functioning the same anymore. The mod developers have been notified of this and are advised to update their mods.

**Comment by Sajidur78** [comment]
The issue has been fixed from the mod developers. Make sure you have the latest version of those mods.
