### ISSUE TITLE
Better Fxpipeline doesn't work

### ISSUE THREAD

**Issue by WildberrySherbert** [hedge-dev/HE1ML#2]
Self explainatory, Better Fxpipeline doesn't do anything, no crashes, but no graphical enhancements.
![71340_20230725213939_1](https://github.com/hedge-dev/HE1ML/assets/140579978/dd97b2a0-812a-4feb-9492-7e3e7d43f432)
Chemical Plant usually has much darker lighting with Better Fxpipeline working, so if it looks like this and you have Better Fxpipeline enabled then something is definitely not working correctly.

**Comment by RagdollClash** [comment]
BetterFxPipeline is working, as you normally can't have directional shadows in Generations.
![image](https://github.com/hedge-dev/HE1ML/assets/15317421/538dcf04-867d-40fc-96fd-293db2fc5986)

**Comment by Sajidur78** [comment]
Were you previously playing on fullscreen mode and switched to borderless or windowed recently? Gens just looks darker in general when fullscreen is used because the brightness option doesn't work otherwise.

**Comment by RagdollClash** [comment]
Additionally: If you're using the DirectX 11 mod, the gamma correction won't be applied at all as it's not implemented in said mod.
